#Make sure you have gcc version 9.1 or higher to benefit from c++17 language
#You can check current version by running <gcc --version>

TreeSearch: TreeSearch.cpp
	g++ -std=c++17 TreeSearch.cpp -o TreeSearch
